import type { ExportSettings } from "../export/OfflineAnimationRenderer";

interface Props { open: boolean; settings: ExportSettings; running: boolean; progress: string; current: number; total: number; ffmpegReady: boolean; onSettings(value: ExportSettings): void; onExport(): void; onCancel(): void; onClose(): void }
const resolutions = ["1920x1080", "1280x720", "1080x1080", "1080x1920", "3840x2160"];

export function ExportPanel(props: Props) {
  if (!props.open) return null;
  const set = (patch: Partial<ExportSettings>) => props.onSettings({ ...props.settings, ...patch });
  const percent = props.total ? props.current / props.total * 100 : 0;
  return <div className="export-backdrop"><section className="export-panel"><header><div><small>BACKGROUND DETERMINISTIC RENDER</small><h2>EXPORT VIDEO</h2></div><button onClick={props.onClose}>×</button></header>
    <div className="export-ready">{props.settings.renderer === "remotion" ? "Remotion background renderer" : "Legacy browser renderer"}<b className={props.ffmpegReady ? "ready" : "missing"}>{props.ffmpegReady ? "✓ Ready" : "Unavailable"}</b></div>
    <div className="export-presets"><button onClick={() => set({ format: "mp4", width: 1920, height: 1080, fps: 60, quality: "High", background: "project", fit: "Fit" })}>YouTube 1080p 60</button><button onClick={() => set({ format: "mp4", width: 1080, height: 1920, fps: 60, quality: "High", background: "project", fit: "Fit" })}>Shorts 1080×1920</button><button onClick={() => set({ format: "png", width: 1920, height: 1080, fps: 60, quality: "High", background: "transparent", fit: "Fit" })}>Transparent PNG</button><button onClick={() => set({ format: "mp4", width: 1920, height: 1080, fps: 60, quality: "High", background: "solid", color: "#00FF00", fit: "Fit" })}>Green Screen</button></div>
    <label>Format<select value={props.settings.format} onChange={(event) => set({ format: event.target.value as ExportSettings["format"], background: event.target.value === "mp4" && props.settings.background === "transparent" ? "project" : props.settings.background })}><option value="mp4">MP4 · H.264</option><option value="webm">WebM · VP9</option><option value="png">PNG Sequence</option></select></label>
    <label>Resolution<select value={resolutions.includes(`${props.settings.width}x${props.settings.height}`) ? `${props.settings.width}x${props.settings.height}` : "custom"} onChange={(event) => { if (event.target.value === "custom") return; const [width, height] = event.target.value.split("x").map(Number); set({ width, height }); }}>{resolutions.map((value) => <option key={value}>{value}</option>)}<option value="custom">Custom</option></select></label>
    <div className="export-grid"><label>Width<input type="number" min="64" max="7680" value={props.settings.width} onChange={(event) => set({ width: Math.max(64, Number(event.target.value)) })}/></label><label>Height<input type="number" min="64" max="7680" value={props.settings.height} onChange={(event) => set({ height: Math.max(64, Number(event.target.value)) })}/></label></div>
    <div className="export-grid"><label>Frame Rate<select value={props.settings.fps} onChange={(event) => set({ fps: Number(event.target.value) as ExportSettings["fps"] })}><option>24</option><option>30</option><option>60</option></select></label><label>Fit<select value={props.settings.fit} onChange={(event) => set({ fit: event.target.value as ExportSettings["fit"] })}><option>Fit</option><option>Fill</option><option>Stretch</option></select></label></div>
    <div className="export-grid"><label>Quality<select value={props.settings.quality} onChange={(event) => set({ quality: event.target.value as ExportSettings["quality"] })}><option>Draft</option><option>Standard</option><option>High</option><option>Maximum</option></select></label><label>Background<select value={props.settings.background} onChange={(event) => set({ background: event.target.value as ExportSettings["background"] })}><option value="project">Project Background</option><option value="transparent" disabled={props.settings.format === "mp4"}>Transparent</option><option value="solid">Solid Color</option></select></label></div>
    {props.settings.background === "solid" && <div className="color-row"><input type="color" value={props.settings.color} onChange={(event) => set({ color: event.target.value.toUpperCase() })}/><input value={props.settings.color} onChange={(event) => /^#[0-9a-f]{6}$/i.test(event.target.value) && set({ color: event.target.value.toUpperCase() })}/>{[["White", "#FFFFFF"], ["Black", "#000000"], ["Green", "#00FF00"], ["Blue", "#0000FF"]].map(([name, color]) => <button key={name} onClick={() => set({ color })}>{name}</button>)}</div>}
    <div className="export-checks"><label><input type="checkbox" checked={props.settings.includeAudio} onChange={(event) => set({ includeAudio: event.target.checked })}/> Include audio</label><label><input type="checkbox" checked={props.settings.keepFrames} onChange={(event) => set({ keepFrames: event.target.checked })}/> Keep render frames</label></div>
    <details className="export-advanced"><summary>Performance & troubleshooting</summary>
      <label>Concurrency<select value={props.settings.concurrency} onChange={(event) => set({ concurrency: event.target.value as ExportSettings["concurrency"] })}><option value="auto">Auto (recommended)</option><option value="low">Low · 25%</option><option value="medium">Medium · 50%</option><option value="high">High · 75%</option></select></label>
      <label>Renderer<select value={props.settings.renderer} onChange={(event) => set({ renderer: event.target.value as ExportSettings["renderer"] })}><option value="remotion">Remotion background renderer</option><option value="legacy">Legacy browser renderer</option></select></label>
      {props.settings.renderer === "legacy" && <label>FFmpeg path<input value={props.settings.ffmpegPath ?? ""} placeholder="Auto detect (ffmpeg)" onChange={(event) => set({ ffmpegPath: event.target.value.trim() || undefined })}/></label>}
    </details>
    {props.running && <div className="export-progress"><span>{props.progress}</span><b>{props.current} / {props.total} · {percent.toFixed(1)}%</b><i><em style={{ width: `${percent}%` }}/></i></div>}
    <footer>{props.running && <button onClick={props.onCancel}>CANCEL EXPORT</button>}<button onClick={props.onClose}>{props.running ? "RUN IN BACKGROUND" : "CANCEL"}</button><button className="primary-action" disabled={props.running || !props.ffmpegReady} onClick={props.onExport}>EXPORT</button></footer>
  </section></div>;
}
