import { eyeExpressions, productionVisemes } from "../character/FaceAssets";
import { browPresets } from "../character/EyePresets";
import type { BrowSideState, EyeSideState, FaceAssetState, FaceCalibration, FaceState } from "../project/schema";
import { FaceRig } from "./FaceRig";

interface Props { open: boolean; face: FaceState; calibration: FaceCalibration; assets: FaceAssetState; onFace(patch: Partial<FaceState>): void; onAssets(next: FaceAssetState): void; onKeyframeGlasses(): void; onClose(): void }
export function EyeDesignLab({ open, face, calibration, assets, onFace, onAssets, onKeyframeGlasses, onClose }: Props) {
  if (!open) return null;
  const setEye = (side: "left" | "right", patch: Partial<EyeSideState>) => onFace({ eyeSystem: { ...face.eyeSystem, [side]: { ...face.eyeSystem[side], ...patch } } });
  const setBrow = (side: "left" | "right", patch: Partial<BrowSideState>) => onFace({ browSystem: { ...face.browSystem, [side]: { ...face.browSystem[side], ...patch } } });
  const glasses = face.accessories.sunglasses, setGlasses = (patch: Partial<typeof glasses>) => onFace({ accessories: { ...face.accessories, sunglasses: { ...glasses, ...patch } } });
  const cry = face.cryControls, setCry = (patch: Partial<typeof cry>) => onFace({ cryControls: { ...cry, ...patch } });
  const applyPair = (expression: FaceState["eyeExpression"]) => onFace({ eyeExpression: expression, eyeSystem: { left: { ...face.eyeSystem.left, expression: "inherit" }, right: { ...face.eyeSystem.right, expression: "inherit" } } });
  return <div className="eye-lab-backdrop"><section className="eye-lab">
    <header><div><small>ALGOWZXD 2024 · GENERATED RASTER FACE V1</small><h2>MODULAR FACE ASSET LAB</h2></div><button onClick={onClose}>×</button></header>
    <div className="eye-lab-preview"><svg viewBox="790 65 210 245"><g transform="matrix(.65 0 0 .65 221.95 -72.55)"><image href="/production_character/illustrator2024/head/head.svg" x="0" y="0" width="1920" height="1080"/><image href="/production_character/illustrator2024/head/ears.svg" x="0" y="0" width="1920" height="1080"/><image href="/production_character/illustrator2024/head/hair.svg" x="0" y="0" width="1920" height="1080"/></g><FaceRig face={{ ...face, previewAutomation: false }} calibration={calibration} assets={assets} time={0} playing={false}/></svg><div><b>ACTUAL ALGOWZXD FACE PREVIEW</b><span>Expression + asymmetry + gaze + blink + brows + accessory</span></div></div>
    <div className="eye-lab-toolbar"><label>Active eye pack<select value={assets.activeEyePack} onChange={(event) => onAssets({ ...assets, activeEyePack: event.target.value as FaceAssetState["activeEyePack"] })}><option value="raster-v1">Generated Raster V1</option><option value="expressive">Expressive fallback</option><option value="classic">Classic Algowzxd</option><option value="anime-comedy">Anime / Comedy</option><option value="custom">Custom</option></select></label><button onClick={() => window.open("/face/eye-contact-sheet", "_blank")}>CONTACT SHEET</button><button onClick={() => window.open("/face/cry-qa", "_blank")}>CRY QA</button><button onClick={() => applyPair("neutral")}>RESET EYES</button></div>
    <div className="eye-lab-columns"><section><h3>MODULAR FACE</h3><label>Mouth<select value={face.mouth} onChange={(event) => onFace({ mouth: event.target.value as FaceState["mouth"] })}>{productionVisemes.map((mouth) => <option key={mouth}>{mouth}</option>)}</select></label><label>Face FX<select value={face.faceFx} onChange={(event) => onFace({ faceFx: event.target.value as FaceState["faceFx"] })}><option value="auto">Auto</option><option value="none">None</option><option value="angryShadow">Angry shadow</option></select></label><label>Extra FX<select value={face.extraFaceFx} onChange={(event) => onFace({ extraFaceFx: event.target.value as FaceState["extraFaceFx"] })}><option value="auto">Auto</option><option value="none">None</option><option value="angerCross01">Anger cross 01</option><option value="angerCross02">Anger cross 02</option><option value="angerVein01">Anger vein 01</option></select></label></section><section><h3>TEARS · HAIR · ACCESSORY</h3><label>Tears<select value={face.tears} onChange={(event) => onFace({ tears: event.target.value as FaceState["tears"] })}><option value="auto">Auto from expression</option><option value="none">None</option><option value="stream">Tear stream</option><option value="waterfall">Waterfall</option></select></label><label>Hair<select value={face.hairStyle} onChange={(event) => onFace({ hairStyle: event.target.value as FaceState["hairStyle"] })}><option value="canonical">Canonical Algowzxd</option></select></label><label>Accessory<select value={glasses.visible ? "sunglasses" : "none"} onChange={(event) => setGlasses({ visible: event.target.value === "sunglasses" })}><option value="none">None</option><option value="sunglasses">Stylish sunglasses</option></select></label></section></div>
    <section className="glasses-lab"><h3>CRY_CONTROLS · DETERMINISTIC 2D</h3><label>Cry State<select value={cry.state} onChange={(event) => setCry({ state: event.target.value as typeof cry.state })}><option value="auto">Auto from expression</option><option value="off">Off</option><option value="watery">Watery</option><option value="aboutToCry">About to cry</option><option value="firstTear">First tear</option><option value="cryStream">Cry stream</option><option value="cryingHard">Crying hard</option><option value="waterfallExtreme">Waterfall extreme</option></select></label><label className="glasses-toggle"><input type="checkbox" checked={cry.enableShake} onChange={(event) => setCry({ enableShake: event.target.checked })}/> Enable Cry Shake</label><label className="glasses-toggle"><input type="checkbox" checked={cry.enableTears} onChange={(event) => setCry({ enableTears: event.target.checked })}/> Enable Tears</label><label className="glasses-toggle"><input type="checkbox" checked={cry.showFaceMatte} onChange={(event) => setCry({ showFaceMatte: event.target.checked })}/> Show Face Matte</label><Slider label="Cry Shake Amount" min={0} max={2.5} value={cry.shakeAmount} onChange={(shakeAmount) => setCry({ shakeAmount })}/><Slider label="Cry Shake Frequency" min={8} max={16} value={cry.shakeFrequency} onChange={(shakeFrequency) => setCry({ shakeFrequency })}/><Slider label="Vertical Ratio" min={.4} max={.7} value={cry.shakeVerticalRatio} onChange={(shakeVerticalRatio) => setCry({ shakeVerticalRatio })}/><Slider label="Shake Rotation" min={0} max={.3} value={cry.shakeRotation} onChange={(shakeRotation) => setCry({ shakeRotation })}/><Slider label="Tear Flow Speed" min={8} max={48} step={1} value={cry.flowSpeed} onChange={(flowSpeed) => setCry({ flowSpeed })}/><Slider label="Turbulence Amount" min={0} max={6} value={cry.turbulenceAmount} onChange={(turbulenceAmount) => setCry({ turbulenceAmount })}/><Slider label="Turbulence Size" min={15} max={35} step={1} value={cry.turbulenceSize} onChange={(turbulenceSize) => setCry({ turbulenceSize })}/><Slider label="Tear Opacity" min={0} max={1} value={cry.opacity} onChange={(opacity) => setCry({ opacity })}/><Slider label="Tear Amount" min={.5} max={1.3} value={cry.amount} onChange={(amount) => setCry({ amount })}/></section>
    <div className="eye-expression-library">{eyeExpressions.map((expression) => <button key={expression} className={face.eyeExpression === expression ? "active" : ""} onClick={() => applyPair(expression)}>{expression}</button>)}</div>
    <div className="eye-lab-columns">{(["left", "right"] as const).map((side) => <section key={side}><h3>{side.toUpperCase()} EYE</h3><label>Expression<select value={face.eyeSystem[side].expression} onChange={(event) => setEye(side, { expression: event.target.value as EyeSideState["expression"] })}><option value="inherit">Use pair preset</option>{eyeExpressions.map((expression) => <option key={expression}>{expression}</option>)}</select></label><Slider label="Scale X" min={.6} max={1.7} value={face.eyeSystem[side].scaleX} onChange={(scaleX) => setEye(side, { scaleX })}/><Slider label="Scale Y" min={.6} max={1.7} value={face.eyeSystem[side].scaleY} onChange={(scaleY) => setEye(side, { scaleY })}/><Slider label="Openness" min={0} max={1.4} value={face.eyeSystem[side].openness} onChange={(openness) => setEye(side, { openness })}/><Slider label="Squint" min={0} max={1} value={face.eyeSystem[side].squint} onChange={(squint) => setEye(side, { squint })}/><Slider label="Rotation" min={-20} max={20} step={1} value={face.eyeSystem[side].rotation} onChange={(rotation) => setEye(side, { rotation })}/><Slider label="Pupil" min={.2} max={1.8} value={face.eyeSystem[side].pupilScale} onChange={(pupilScale) => setEye(side, { pupilScale })}/></section>)}</div>
    <div className="eye-lab-columns">{(["left", "right"] as const).map((side) => <section key={side}><h3>{side.toUpperCase()} EYEBROW</h3><label>Preset<select value={face.browSystem[side].preset} onChange={(event) => setBrow(side, { preset: event.target.value as BrowSideState["preset"] })}><option value="auto">Follow eye expression</option>{browPresets.map((preset) => <option key={preset}>{preset}</option>)}</select></label><Slider label="Height" min={-12} max={12} step={1} value={face.browSystem[side].y} onChange={(y) => setBrow(side, { y })}/><Slider label="Rotation" min={-25} max={25} step={1} value={face.browSystem[side].rotation} onChange={(rotation) => setBrow(side, { rotation })}/><Slider label="Inner raise" min={-10} max={10} step={1} value={face.browSystem[side].innerHeight} onChange={(innerHeight) => setBrow(side, { innerHeight })}/><Slider label="Outer raise" min={-10} max={10} step={1} value={face.browSystem[side].outerHeight} onChange={(outerHeight) => setBrow(side, { outerHeight })}/><Slider label="Curve" min={-8} max={8} step={1} value={face.browSystem[side].curve} onChange={(curve) => setBrow(side, { curve })}/></section>)}</div>
    <section className="glasses-lab"><h3>ACCESSORIES · BLACK SUNGLASSES</h3><label className="glasses-toggle"><input type="checkbox" checked={glasses.visible} onChange={(event) => setGlasses({ visible: event.target.checked })}/> {glasses.visible ? "ON" : "OFF"}</label><button onClick={onKeyframeGlasses}>KEYFRAME ON/OFF AT PLAYHEAD</button><Slider label="Scale" min={.65} max={1.5} value={glasses.scale} onChange={(scale) => setGlasses({ scale })}/><Slider label="X" min={-30} max={30} step={1} value={glasses.offsetX} onChange={(offsetX) => setGlasses({ offsetX })}/><Slider label="Y" min={-30} max={30} step={1} value={glasses.offsetY} onChange={(offsetY) => setGlasses({ offsetY })}/><Slider label="Rotation" min={-20} max={20} step={1} value={glasses.rotation} onChange={(rotation) => setGlasses({ rotation })}/></section>
    <footer><span>All controls are saved in the project and remain editable.</span><button className="primary-action" onClick={onClose}>DONE</button></footer>
  </section></div>;
}
function Slider({ label, value, min, max, step = .05, onChange }: { label: string; value: number; min: number; max: number; step?: number; onChange(value: number): void }) { return <label className="eye-lab-slider"><span>{label}</span><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))}/><b>{value.toFixed(step < 1 ? 2 : 0)}</b></label>; }
