const base = "http://localhost:4173";
const settings = { format: "mp4", width: 1920, height: 1080, fps: 60, quality: "High", background: "project", color: "#E8EDF2", fit: "Fit", includeAudio: false, keepFrames: false };
const started = await fetch(`${base}/api/export/start`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ settings, total: 1 }) });
if (!started.ok) throw new Error(await started.text());
const { id } = await started.json();
const sample = join(tmpdir(), `algowzxd-export-smoke-${randomUUID()}.png`);
const generated = spawnSync("ffmpeg", ["-y", "-f", "lavfi", "-i", "color=c=red:s=2x2", "-frames:v", "1", sample], { windowsHide: true });
if (generated.status !== 0) throw new Error("Could not create export smoke-test frame.");
const png = await readFile(sample); await rm(sample, { force: true });
const frame = await fetch(`${base}/api/export/frame?id=${id}&index=0`, { method: "POST", body: png });
if (!frame.ok) throw new Error(await frame.text());
const finished = await fetch(`${base}/api/export/finish`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id }) });
if (!finished.ok) throw new Error(await finished.text());
const result = await finished.json();
const output = await fetch(`${base}${result.downloadUrl}`); if (!output.ok || !(await output.arrayBuffer()).byteLength) throw new Error("Exported file could not be downloaded.");
await fetch(`${base}/api/export/cancel?id=${id}`, { method: "POST" });
console.log(JSON.stringify(result));
import { spawnSync } from "node:child_process";
import { readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { randomUUID } from "node:crypto";
